apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mundia-prod

helmGlobals:
  chartHome: ../../../helm
helmCharts:
  - name: mundia-service
    releaseName: circulation
    namespace: mundia-prod
    valuesFile: values-circulation.yaml
    includeCRDs: false
