[versions]
spring-boot = "4.1.0"
kotlin = "2.3.21"
jooq = "3.21.5"
protobuf-java = "4.35.1"
protobuf-gradle-plugin = "0.9.6"
grpc-java = "1.80.0"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
jooq-codegen = { id = "org.jooq.jooq-codegen-gradle", version.ref = "jooq" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-gradle-plugin" }
