{{- if and .Values.migration.enabled .Values.migration.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mundia-service.fullname" . }}-migration
  labels:
    {{- include "mundia-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-20"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  podSelector:
    matchLabels:
      {{- include "mundia-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: migration
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- range .Values.migration.networkPolicy.egressCidrs }}
    - to:
        - ipBlock:
            cidr: {{ .cidr }}
      ports:
        {{- toYaml .ports | nindent 8 }}
    {{- end }}
{{- end }}
