{{- if .Values.migration.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mundia-service.migrationServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mundia-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-3"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-30"
    helm.sh/hook-delete-policy: before-hook-creation
automountServiceAccountToken: false
{{- end }}
