{{- if and .Values.migration.enabled .Values.migration.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "mundia-service.fullname" . }}-migration
  labels:
    {{- include "mundia-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-20"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  refreshInterval: {{ .Values.migration.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.migration.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.migration.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.migration.externalSecret.targetName }}
    creationPolicy: {{ .Values.migration.externalSecret.creationPolicy }}
    deletionPolicy: {{ .Values.migration.externalSecret.deletionPolicy }}
  data:
    {{- range .Values.migration.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
        property: {{ .property }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    {{- end }}
{{- end }}
