apiVersion: v1
kind: Namespace
metadata:
  name: mundia-staging-migrations
  labels:
    mundiapolis.io/environment: staging
    mundiapolis.io/purpose: migrations
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
