apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  conditions:
    - namespaces:
        - mundia-dev
        - mundia-staging
        - mundia-prod
  provider:
    aws:
      service: SecretsManager
      region: REPLACE_AWS_REGION

