apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: otel-exporter
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: otel-exporter-auth
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: OTEL_EXPORTER_AUTHORIZATION
      remoteRef:
        key: mundia/REPLACE_ENV/platform/otel
        property: authorization
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
