apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mundia-dev-migrations
resources:
  - namespace.yaml
  - ../../base

helmGlobals:
  chartHome: ../../../../helm
helmCharts:
  - name: mundia-service
    releaseName: circulation
    namespace: mundia-dev-migrations
    valuesFile: values-circulation-migration.yaml
    includeCRDs: false

patches:
  - target:
      kind: SecretStore
      name: aws-secrets-manager
    patch: |-
      - op: replace
        path: /spec/provider/aws/region
        value: REPLACE_DEV_AWS_REGION
