/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the safe browser-session projection */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bootstrap a CSRF token for state-changing requests */
        get: operations["getCsrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invalidate the current browser session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the catalog through the BFF */
        get: operations["searchCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/learning-resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search verified open-learning resources through delegated authorization */
        get: operations["searchLearningResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/learning-resources/{resourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one verified open-learning resource */
        get: operations["getLearningResource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/learning-resource-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List verified learning-resource categories */
        get: operations["listLearningResourceCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/membership/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated member's profile through delegated authorization */
        get: operations["getOwnMembershipProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/circulation/eligibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated member's circulation eligibility */
        get: operations["getOwnCirculationEligibility"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/circulation/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated member's loan history */
        get: operations["getOwnLoans"];
        put?: never;
        /** Request a loan for the authenticated member */
        post: operations["requestOwnLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/circulation/loans/{loanId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel the authenticated member's pending loan request */
        post: operations["cancelOwnLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/circulation/loans/{loanId}/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renew the authenticated member's eligible active loan */
        post: operations["renewOwnLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/circulation/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated member's reservation history */
        get: operations["getOwnReservations"];
        put?: never;
        /** Place a reservation for the authenticated member */
        post: operations["placeOwnReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/circulation/reservations/{reservationId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel the authenticated member's open reservation */
        post: operations["cancelOwnReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated member's notification inbox */
        get: operations["getOwnNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Idempotently mark an owned notification as read */
        patch: operations["markOwnNotificationReadThroughBff"];
        trace?: never;
    };
    "/api/v1/notifications/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOwnNotificationPreferenceThroughBff"];
        put: operations["updateOwnNotificationPreferenceThroughBff"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/digital-content/editions/{editionId}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDownloadAvailabilityThroughBff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/digital-content/assets/{assetId}/authorizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["authorizeDownloadThroughBff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/digital-content/external-resources/{resourceId}/authorizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["authorizeExternalResourceDownloadThroughBff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        EditionDownloadAvailability: {
            /** Format: uuid */
            editionId: string;
            downloadable: boolean;
            formats: components["schemas"]["DownloadableFormat"][];
        };
        DownloadableFormat: {
            /** Format: uuid */
            assetId: string;
            /** @enum {string} */
            format: "PDF" | "EPUB";
            /** @enum {string} */
            mediaType: "application/pdf" | "application/epub+zip";
            /** Format: int64 */
            sizeBytes: number;
            sha256: string;
            licenseExpression: string;
            attribution: string;
        };
        DownloadAuthorization: {
            /** Format: uuid */
            authorizationId: string;
            /** Format: uuid */
            assetId: string;
            /** Format: uri */
            downloadUrl: string;
            /** Format: date-time */
            expiresAt: string;
        };
        ExternalDownloadAuthorization: {
            /** Format: uuid */
            authorizationId: string;
            /** Format: uuid */
            resourceId: string;
            sourceProvider: string;
            /** @enum {string} */
            licenseExpression: "CC-BY-4.0" | "CC-BY-SA-4.0" | "CC0-1.0" | "PDM-1.0";
            /** Format: uri */
            downloadUrl: string;
        };
        Session: {
            authenticated: boolean;
            displayName?: string | null;
        };
        CsrfToken: {
            headerName: string;
            parameterName: string;
            token: string;
        };
        CatalogSearch: {
            editions: components["schemas"]["CatalogEdition"][];
            total: number;
            page: number;
            totalPages: number;
        };
        CatalogEdition: {
            /** Format: uuid */
            editionId: string;
            /** Format: uuid */
            workId: string;
            title: string;
            isbn: string;
            publisher: string;
            publicationYear: number;
            language: string;
            pageCount: number;
            /** Format: uri */
            coverUrl?: string | null;
            coverColor?: string | null;
            /** Format: uri */
            videoUrl?: string | null;
            totalCopies: number;
            availableCopies: number;
            isActive: boolean;
        };
        LearningResourcePage: {
            resources: components["schemas"]["LearningResource"][];
            total: number;
            page: number;
            totalPages: number;
        };
        LearningResource: {
            /** Format: uuid */
            resourceId: string;
            title: string;
            author: string | null;
            description: string | null;
            category: string;
            language: string;
            /** Format: uri */
            coverUrl: string | null;
            coverAlt: string | null;
            sourceName: string;
            /** Format: uri */
            sourceUrl: string;
            /** @enum {string} */
            licenseExpression: "CC-BY" | "CC-BY-SA" | "CC0" | "PUBLIC-DOMAIN";
            /** Format: uri */
            licenseUrl: string;
            /** @enum {string} */
            accessMode: "DOWNLOAD" | "READ_AT_SOURCE";
            /** Format: uri */
            readUrl: string | null;
        };
        MemberProfile: {
            /** Format: uuid */
            memberId: string;
            /** Format: email */
            email: string;
            fullName: string;
            universityId: number;
            /** @enum {string} */
            status: "PENDING" | "APPROVED" | "REJECTED";
            /** @enum {string} */
            role: "USER" | "ADMIN" | "SUPER_ADMIN";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CirculationEligibility: {
            /** Format: uuid */
            memberId: string;
            /** @enum {string} */
            status: "ELIGIBLE" | "INELIGIBLE" | "SUSPENDED";
            reasonCode: string | null;
            /** Format: int64 */
            sourceVersion: number;
            /** Format: date-time */
            sourceOccurredAt: string;
        };
        RequestLoan: {
            /** Format: uuid */
            editionId: string;
        };
        LoanCommand: {
            /** Format: uuid */
            loanId: string;
            /** Format: uuid */
            memberId: string;
            /** Format: uuid */
            editionId: string;
            /** Format: uuid */
            copyId: string | null;
            /** @enum {string} */
            status: "REQUESTED" | "ACTIVE" | "RETURNED" | "REJECTED" | "CANCELLED";
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            checkedOutAt: string | null;
            /** Format: date-time */
            dueAt: string | null;
            /** Format: date-time */
            returnedAt: string | null;
            renewalCount: number;
            /** Format: int64 */
            version: number;
        };
        MemberLoanPage: {
            /** Format: uuid */
            memberId: string;
            items: components["schemas"]["LoanHistoryItem"][];
            nextCursor: string | null;
        };
        LoanHistoryItem: {
            /** Format: uuid */
            loanId: string;
            /** Format: uuid */
            memberId: string;
            /** Format: uuid */
            editionId: string;
            /** Format: uuid */
            copyId: string | null;
            /** @enum {string} */
            status: "REQUESTED" | "ACTIVE" | "RETURNED" | "REJECTED" | "CANCELLED";
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            checkedOutAt: string | null;
            /** Format: date-time */
            dueAt: string | null;
            /** Format: date-time */
            returnedAt: string | null;
            /** Format: date-time */
            rejectedAt: string | null;
            renewalCount: number;
            /** Format: int64 */
            version: number;
        };
        RequestReservation: {
            /** Format: uuid */
            editionId: string;
        };
        ReservationCommand: {
            /** Format: uuid */
            reservationId: string;
            /** Format: uuid */
            memberId: string;
            /** Format: uuid */
            editionId: string;
            /** Format: uuid */
            copyId: string | null;
            /** @enum {string} */
            status: "WAITING" | "READY" | "FULFILLED" | "CANCELLED" | "EXPIRED";
            /** Format: date-time */
            placedAt: string;
            /** Format: date-time */
            readyAt: string | null;
            /** Format: date-time */
            expiresAt: string | null;
            /** Format: date-time */
            fulfilledAt: string | null;
            /** Format: date-time */
            cancelledAt: string | null;
            /** Format: int64 */
            version: number;
        };
        MemberReservationPage: {
            /** Format: uuid */
            memberId: string;
            items: components["schemas"]["ReservationCommand"][];
            nextCursor: string | null;
        };
        NotificationItem: {
            /** Format: uuid */
            notificationId: string;
            /** @enum {string} */
            category: "DUE_SOON" | "OVERDUE" | "HOLD_READY" | "ACCOUNT_STATUS" | "GENERAL";
            subject: string;
            body: string;
            /** Format: date-time */
            occurredAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            readAt: string | null;
        };
        NotificationPage: {
            /** Format: uuid */
            memberId: string;
            items: components["schemas"]["NotificationItem"][];
            nextCursor: string | null;
        };
        NotificationPreference: {
            /** Format: uuid */
            memberId: string;
            emailEnabled: boolean;
            dueSoonEnabled: boolean;
            overdueEnabled: boolean;
            holdReadyEnabled: boolean;
            accountStatusEnabled: boolean;
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            updatedAt: string | null;
        };
        UpdateNotificationPreference: {
            emailEnabled: boolean;
            dueSoonEnabled: boolean;
            overdueEnabled: boolean;
            holdReadyEnabled: boolean;
            accountStatusEnabled: boolean;
        };
        Problem: {
            /** Format: uri-reference */
            type?: string;
            title: string;
            status: number;
            detail: string;
            /** Format: uri-reference */
            instance?: string;
            code: string;
        };
    };
    responses: {
        /** @description Stable non-sensitive error response */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Loan command committed or its original result replayed */
        LoanCommandSucceeded: {
            headers: {
                "Cache-Control"?: "no-store";
                "Idempotency-Replayed"?: "true" | "false";
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LoanCommand"];
            };
        };
        /** @description Reservation command committed or its original result replayed */
        ReservationCommandSucceeded: {
            headers: {
                "Cache-Control"?: "no-store";
                "Idempotency-Replayed"?: "true" | "false";
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ReservationCommand"];
            };
        };
    };
    parameters: {
        LoanId: string;
        ReservationId: string;
        /** @description Actor-scoped command key. Reuse with a different request is rejected. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authentication state */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
        };
    };
    getCsrfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF token and submission fields */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfToken"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session invalidated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description CSRF token missing or invalid */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchCatalog: {
        parameters: {
            query?: {
                query?: string;
                genre?: string;
                authorId?: string;
                availableOnly?: boolean;
                minRating?: number;
                sortBy?: "title" | "rating" | "publicationYear";
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded catalog search results */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogSearch"];
                };
            };
            400: components["responses"]["Problem"];
            /** @description Browser session missing or user authorization must be renewed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    searchLearningResources: {
        parameters: {
            query?: {
                query?: string;
                category?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded verified learning-resource page */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningResourcePage"];
                };
            };
            400: components["responses"]["Problem"];
            /** @description Browser session missing or user authorization must be renewed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    getLearningResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verified learning-resource metadata */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningResource"];
                };
            };
            /** @description Browser session missing or user authorization must be renewed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    listLearningResourceCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unique sorted categories */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Browser session missing or user authorization must be renewed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    getOwnMembershipProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authoritative membership profile bound to the authenticated session */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberProfile"];
                };
            };
            /** @description Browser session missing or user authorization must be renewed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    getOwnCirculationEligibility: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Caller-bound circulation eligibility projection */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CirculationEligibility"];
                };
            };
            /** @description Browser session missing or user authorization must be renewed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    getOwnLoans: {
        parameters: {
            query?: {
                status?: "REQUESTED" | "ACTIVE" | "RETURNED" | "REJECTED" | "CANCELLED";
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Caller-bound keyset page */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberLoanPage"];
                };
            };
            400: components["responses"]["Problem"];
            /** @description Browser session missing or user authorization must be renewed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    requestOwnLoan: {
        parameters: {
            query?: never;
            header: {
                /** @description Actor-scoped command key. Reuse with a different request is rejected. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestLoan"];
            };
        };
        responses: {
            /** @description Loan request committed or its original result replayed */
            201: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "Idempotency-Replayed"?: "true" | "false";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanCommand"];
                };
            };
            400: components["responses"]["Problem"];
            /** @description Browser session missing or user authorization must be renewed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    cancelOwnLoan: {
        parameters: {
            query?: never;
            header: {
                /** @description Actor-scoped command key. Reuse with a different request is rejected. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                loanId: components["parameters"]["LoanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["LoanCommandSucceeded"];
            400: components["responses"]["Problem"];
            /** @description Browser session missing or user authorization must be renewed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    renewOwnLoan: {
        parameters: {
            query?: never;
            header: {
                /** @description Actor-scoped command key. Reuse with a different request is rejected. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                loanId: components["parameters"]["LoanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["LoanCommandSucceeded"];
            400: components["responses"]["Problem"];
            /** @description Browser session missing or user authorization must be renewed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    getOwnReservations: {
        parameters: {
            query?: {
                status?: "WAITING" | "READY" | "FULFILLED" | "CANCELLED" | "EXPIRED";
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Caller-bound keyset page */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberReservationPage"];
                };
            };
            400: components["responses"]["Problem"];
            /** @description Browser session missing or user authorization must be renewed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    placeOwnReservation: {
        parameters: {
            query?: never;
            header: {
                /** @description Actor-scoped command key. Reuse with a different request is rejected. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestReservation"];
            };
        };
        responses: {
            201: components["responses"]["ReservationCommandSucceeded"];
            400: components["responses"]["Problem"];
            /** @description Browser session missing or user authorization must be renewed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    cancelOwnReservation: {
        parameters: {
            query?: never;
            header: {
                /** @description Actor-scoped command key. Reuse with a different request is rejected. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                reservationId: components["parameters"]["ReservationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ReservationCommandSucceeded"];
            400: components["responses"]["Problem"];
            /** @description Browser session missing or user authorization must be renewed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    getOwnNotifications: {
        parameters: {
            query?: {
                status?: "ALL" | "READ" | "UNREAD";
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Caller-bound notification page */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPage"];
                };
            };
            400: components["responses"]["Problem"];
            /** @description Browser session missing or user authorization must be renewed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    markOwnNotificationReadThroughBff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notification marked read */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationItem"];
                };
            };
            /** @description Browser session missing or user authorization must be renewed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    getOwnNotificationPreferenceThroughBff: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Caller-bound notification preference */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreference"];
                };
            };
            /** @description Browser session missing or user authorization must be renewed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    updateOwnNotificationPreferenceThroughBff: {
        parameters: {
            query?: never;
            header: {
                "If-Match": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNotificationPreference"];
            };
        };
        responses: {
            /** @description Preference updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreference"];
                };
            };
            400: components["responses"]["Problem"];
            /** @description Browser session missing or user authorization must be renewed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            428: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    getDownloadAvailabilityThroughBff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                editionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rights-safe downloadable formats */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditionDownloadAvailability"];
                };
            };
            /** @description Browser session missing or user authorization must be renewed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    authorizeDownloadThroughBff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Short-lived first-party download authorization */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadAuthorization"];
                };
            };
            /** @description Browser session missing or user authorization must be renewed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    authorizeExternalResourceDownloadThroughBff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audited authorization for the exact verified official file */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalDownloadAuthorization"];
                };
            };
            /** @description Browser session missing or user authorization must be renewed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            502: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
}
