apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - require-immutable-signed-images.yaml
  - require-secure-workloads.yaml
  - restrict-service-exposure.yaml
  - require-tls-ingress.yaml

